### ISSUE TITLE
question about the calculation in cs_fddb_convert_to_darknet.py

### ISSUE THREAD

**Issue by td042** [cezs/FDDB#1]
I was wondering what unit of measure you use in the file for calculating the bounding box? The values are all less than 0. Can I also calculate the values for x, y, length and width of the bounding box in integer pixel values?

**Comment by vaishnavm217** [comment]
This might be very late but just answering it for fun :laughing: 
> I was wondering what unit of measure you use in the file for calculating the bounding box? The values are all less than 0.

FDDB has ellipse as ground truth. Now to convert it to rectangular bounding box, the code converts it approximate box which is supposed to have a max IOU w.r.t the original ellipse that is done by the formula

> Can I also calculate the values for x, y, length and width of the bounding box in integer pixel values?

https://github.com/cezs/FDDB/blob/8fd5ca2e3ffd819797e1a5830ec79ef098591fa1/scripts/cs_fddb_convert_to_darknet.py#L66-L69

Removing the divisions here will get you the original pixel value
